<?php
declare(strict_types=1);
require_once __DIR__ . '/../../includes/bootstrap.php';
require_method('POST'); verify_csrf(); $buyer = require_role(['buyer']);
$listingId = filter_input(INPUT_POST, 'listing_id', FILTER_VALIDATE_INT, ['options' => ['min_range' => 1]]); $quantity = positive_decimal($_POST['quantity'] ?? null); $price = positive_decimal($_POST['offered_price'] ?? null); $message = normalize_text($_POST['message'] ?? '', 500);
if (!$listingId || $quantity === null || $price === null) json_response(false, 'Enter a valid quantity and offered price.', [], 422);
$pdo = db(); $pdo->beginTransaction();
try { $listing = fetch_one('SELECT id, farmer_id, title, quantity_available, minimum_order_quantity FROM produce_listings WHERE id = :id AND status = "active" FOR UPDATE', ['id' => $listingId]); if ($listing === null) throw new RuntimeException('This listing is no longer available.'); if ((int) $listing['farmer_id'] === (int) $buyer['id']) throw new RuntimeException('You cannot submit an offer for your own listing.'); if ($quantity < (float) $listing['minimum_order_quantity'] || $quantity > (float) $listing['quantity_available']) throw new RuntimeException('Your quantity must meet the minimum order and remaining availability.'); $total = round($quantity * $price, 2); $statement = $pdo->prepare('INSERT INTO offers (listing_id, buyer_id, farmer_id, quantity, offered_price, total_amount, message) VALUES (:listing, :buyer, :farmer, :quantity, :price, :total, :message)'); $statement->execute(['listing'=>$listingId,'buyer'=>$buyer['id'],'farmer'=>$listing['farmer_id'],'quantity'=>$quantity,'price'=>$price,'total'=>$total,'message'=>$message ?: null]); $offerId=(int)$pdo->lastInsertId(); $pdo->prepare('INSERT INTO offer_events (offer_id, actor_user_id, event_type, quantity, price, note) VALUES (:offer, :actor, "created", :quantity, :price, :note)')->execute(['offer'=>$offerId,'actor'=>$buyer['id'],'quantity'=>$quantity,'price'=>$price,'note'=>'Buyer offer submitted.']); create_notification((int)$listing['farmer_id'], 'new_offer', 'New buyer offer', $buyer['full_name'].' offered Rs. '.number_format($price,2).'/kg for '.$listing['title'].'.', 'farmer/offers.php', 'offer', $offerId); $pdo->commit(); audit_log((int)$buyer['id'], 'offer_created', 'offers', $offerId, ['listing_id'=>$listingId]); json_response(true, 'Your offer has been sent to the farmer.', ['offer_id'=>$offerId]);
} catch (Throwable $exception) { if ($pdo->inTransaction()) $pdo->rollBack(); json_response(false, $exception instanceof RuntimeException ? $exception->getMessage() : 'The offer could not be submitted. Please try again.', [], 422); }

