<?php
/** Orchard Ledger contact page: a configuration-aware support status with no simulated message submission or invented public channel. */
declare(strict_types=1);

require_once __DIR__ . '/includes/bootstrap.php';
$pageTitle = 'Contact';
$supportMode = SUPPORT_CHANNEL_MODE;
$supportEmail = filter_var(trim(SUPPORT_EMAIL), FILTER_VALIDATE_EMAIL) ?: null;
$supportHelpdeskUrl = filter_var(trim(SUPPORT_HELPDESK_URL), FILTER_VALIDATE_URL) ?: null;
$hasEmailSupport = $supportMode === 'email' && $supportEmail !== null;
$hasHelpdeskSupport = $supportMode === 'helpdesk' && $supportHelpdeskUrl !== null && str_starts_with($supportHelpdeskUrl, 'https://');
require __DIR__ . '/includes/header.php';
?>
<section class="page-intro contact-intro"><div class="site-container"><span class="eyebrow" style="color:var(--clay)">Contact</span><h1><?= $hasEmailSupport || $hasHelpdeskSupport ? 'Reach the verified support channel.' : 'Talk about a practical post-harvest workflow.' ?></h1><p><?= $hasEmailSupport || $hasHelpdeskSupport ? 'Use the approved support channel below for operational questions about the platform. It is shown only after a channel owner has configured and verified it.' : 'For local demonstration, partnership, university, or agricultural-organization enquiries, use the project repository documentation. This build does not publish an unmonitored contact address.' ?></p></div></section>
<section class="section contact-context-section"><div class="site-container"><div class="cta-panel"><div><span class="eyebrow" style="color:var(--clay)">Support channel status</span><?php if ($hasEmailSupport): ?><h2>Support is monitored through the approved email channel.</h2><p>Use this address for customer support. Do not include passwords, reset links, recovery codes, or other account secrets in an email.</p><div class="contact-readiness-row"><span>Verified support email</span><span>Channel owner configured</span><span>Public contact route active</span></div><?php elseif ($hasHelpdeskSupport): ?><h2>Support is monitored through the approved helpdesk.</h2><p>Use the support workspace for customer questions and account follow-through. Do not submit passwords, reset links, recovery codes, or other account secrets.</p><div class="contact-readiness-row"><span>Verified helpdesk</span><span>Channel owner configured</span><span>Public contact route active</span></div><?php else: ?><h2>Support channel awaiting ownership.</h2><p>There is currently no published support email or helpdesk. This deliberate no-channel-yet state prevents an unmonitored inbox, simulated message form, or invented public contact detail from being shown to customers.</p><div class="contact-readiness-row"><span>Current state: unconfigured</span><span>No unmonitored inbox</span><span>Future activation is documented</span></div><?php endif; ?></div><?php if ($hasEmailSupport): ?><a class="button button-primary" href="mailto:<?= e($supportEmail) ?>">Email support</a><?php elseif ($hasHelpdeskSupport): ?><a class="button button-primary" href="<?= e($supportHelpdeskUrl) ?>" rel="noopener noreferrer">Open support</a><?php else: ?><a class="button button-primary" href="<?= e(app_url('about.php')) ?>">Learn about the platform</a><?php endif; ?></div></div></section>
<?php require __DIR__.'/includes/footer.php'; ?>
