<?php
/** Orchard Ledger homepage: field-to-market narrative, live data where available, no invented social proof. */
declare(strict_types=1);
require_once __DIR__ . '/includes/bootstrap.php';

$pageTitle = 'Connect. Store. Sell. Grow.';
$pageDescription = 'A digital marketplace connecting Quetta’s farmers with buyers, cold storage, and reliable transportation.';
$latestListings = fetch_all(
    'SELECT pl.id, pl.title, pl.grade, pl.quantity_available, pl.unit, pl.expected_price, l.district, pc.name AS category_name FROM produce_listings pl JOIN produce_categories pc ON pc.id = pl.category_id JOIN locations l ON l.id = pl.location_id WHERE pl.status = "active" ORDER BY pl.created_at DESC LIMIT 4'
);
$prices = fetch_all('SELECT mp.average_price, mp.unit, pc.name AS category_name, mp.price_date FROM market_prices mp JOIN produce_categories pc ON pc.id = mp.category_id ORDER BY mp.price_date DESC, mp.created_at DESC LIMIT 4');
$metrics = [
    'listings' => (int) (fetch_one('SELECT COUNT(*) AS count FROM produce_listings WHERE status = "active"')['count'] ?? 0),
    'facilities' => (int) (fetch_one('SELECT COUNT(*) AS count FROM storage_facilities WHERE status = "active"')['count'] ?? 0),
    'providers' => (int) (fetch_one('SELECT COUNT(*) AS count FROM transport_providers tp JOIN users u ON u.id = tp.user_id WHERE u.status = "active"')['count'] ?? 0),
];
require __DIR__ . '/includes/header.php';
?>
<section class="hero">
    <div class="hero-content"><span class="eyebrow">Quetta’s agricultural trade network</span><h1>Connect. Store. Sell. Grow.</h1><p>A digital marketplace connecting Quetta’s farmers with buyers, cold storage, and reliable transportation.</p><div class="hero-actions"><a class="button button-primary" href="<?= e(app_url('marketplace/index.php')) ?>">Explore marketplace</a><a class="button button-outline" href="<?= e(app_url('auth/register.php')) ?>">Join as a farmer</a></div><div class="hero-metrics"><div><strong><?= $metrics['listings'] ?></strong><span>active produce listings</span></div><div><strong><?= $metrics['facilities'] ?></strong><span>available storage facilities</span></div><div><strong><?= $metrics['providers'] ?></strong><span>transport providers</span></div></div></div>
</section>

<section class="section section-paper"><div class="site-container"><div class="section-heading"><div><span class="eyebrow" style="color:var(--clay)">How it works</span><h2>From harvest to handover, with a clear next step.</h2></div><p>Quetta AgriLink keeps the after-harvest workflow visible: supply, demand, storage, transport, and delivery status stay connected.</p></div><div class="process-grid"><article class="process-step"><span class="process-number">01 / LIST</span><h3>Make supply visible</h3><p>Farmers publish available produce with grade, quantity, origin, and expected price.</p></article><article class="process-step"><span class="process-number">02 / AGREE</span><h3>Trade with context</h3><p>Buyers compare listings, contact growers, and submit offers through the platform.</p></article><article class="process-step"><span class="process-number">03 / PROTECT</span><h3>Book capacity</h3><p>Check suitable cold-storage facilities and request space when the harvest needs it.</p></article><article class="process-step"><span class="process-number">04 / MOVE</span><h3>Track the handover</h3><p>Request transport and keep order progress visible from pickup through delivery.</p></article></div></div></section>

<section class="section"><div class="site-container"><div class="section-heading"><div><span class="eyebrow" style="color:var(--clay)">Available produce</span><h2>Recent entries from the marketplace.</h2></div><a class="button button-outline" href="<?= e(app_url('marketplace/index.php')) ?>">View all produce</a></div><div class="ledger"><div class="ledger-row ledger-head"><span>Produce & origin</span><span>Grade</span><span>Available</span><span>Expected price</span><span></span></div><?php if ($latestListings === []): ?><div class="ledger-row"><div class="commodity"><div class="commodity-mark"></div><div><h3>No active produce listings yet.</h3><p>New marketplace listings will appear here as growers publish supply.</p></div></div><span></span><span></span><span></span><span></span></div><?php else: foreach ($latestListings as $index => $listing): ?><div class="ledger-row"><div class="commodity"><div class="commodity-mark <?= ['','grape','apricot','pomegranate'][$index % 4] ?>"></div><div><h3><?= e($listing['title']) ?></h3><p><?= e($listing['district']) ?>, Balochistan</p></div></div><span><span class="badge">Grade <?= e($listing['grade']) ?></span></span><span><?= e((string) $listing['quantity_available']) ?> <?= e($listing['unit']) ?></span><span class="price">Rs. <?= number_format((float) $listing['expected_price'], 0) ?>/<?= e($listing['unit']) ?></span><span class="list-action"><a class="button button-quiet" href="<?= e(app_url('marketplace/listing.php?id=' . (int) $listing['id'])) ?>">Inspect</a></span></div><?php endforeach; endif; ?></div></div></section>

<section class="section section-paper"><div class="site-container"><div class="split-feature"><div class="feature-media" style="background-image:url('/manus-storage/quetta-agrilink-storage_a1b611b7.jpg')"></div><div class="feature-copy"><span class="eyebrow" style="color:var(--clay)">Cold storage</span><h2>Protect value when timing matters.</h2><p>Search facilities by location, storage type, capacity, compatible produce, and price. Request space with the quantities and dates you need.</p><ul class="feature-list"><li>Capacity and availability at a glance</li><li>Compatible produce and storage type</li><li>Request, approval, and occupancy status</li></ul><a class="button button-primary" href="<?= e(app_url('storage/index.php')) ?>">Find cold storage</a></div></div></div></section>

<section class="section"><div class="site-container"><div class="split-feature reverse"><div class="feature-media" style="background-image:url('/manus-storage/quetta-agrilink-transport_aac81251.jpg')"></div><div class="feature-copy"><span class="eyebrow" style="color:var(--clay)">Transport</span><h2>Choose the right vehicle for the journey.</h2><p>Locate transport providers by capacity, vehicle type, refrigerated capability, and service areas, then send a clear request for pickup and delivery.</p><ul class="feature-list"><li>Vehicle capacity and refrigeration status</li><li>Service areas across Balochistan</li><li>Practical milestone tracking after acceptance</li></ul><a class="button button-primary" href="<?= e(app_url('transport/index.php')) ?>">Find transport</a></div></div></div></section>

<section class="section section-ink"><div class="site-container"><div class="benefit-grid"><div><span class="eyebrow">Trade intelligence</span><h2>Price awareness belongs alongside the crop, not after the deal.</h2><p>Use current market ranges as a reference when planning listings, buying decisions, storage time, and transport requirements.</p><a class="button button-outline" href="<?= e(app_url('market-prices.php')) ?>">View market prices</a></div><div class="benefit-list"><?php if ($prices === []): ?><article><h3>No market price records yet.</h3><p>Verified price entries will appear here once added by an administrator.</p></article><?php else: foreach ($prices as $price): ?><article><h3><?= e($price['category_name']) ?> <span style="float:right">Rs. <?= number_format((float) $price['average_price'], 0) ?>/<?= e($price['unit']) ?></span></h3><p>Average recorded price · <?= e(date('j M Y', strtotime($price['price_date']))) ?></p></article><?php endforeach; endif; ?></div></div></div></section>

<section class="section section-paper"><div class="site-container"><div class="cta-panel"><div><span class="eyebrow" style="color:var(--clay)">Bring the chain together</span><h2>Start with the work you need to do next.</h2><p>Create the right account type and build a profile that matches your role in the agricultural supply chain.</p></div><a class="button button-primary" href="<?= e(app_url('auth/register.php')) ?>">Join Quetta AgriLink</a></div></div></section>
<?php require __DIR__ . '/includes/footer.php'; ?>

