<?php
/** Quetta Workbench homepage: direct local-market tasks and current records appear before supporting detail. */
declare(strict_types=1);
require_once __DIR__ . '/includes/bootstrap.php';

$pageTitle = 'Quetta AgriLink';
$pageDescription = 'Find produce, storage, transport, and local price records in Quetta.';
$latestListings = fetch_all('SELECT pl.id, pl.title, pl.grade, pl.quantity_available, pl.unit, pl.expected_price, l.district FROM produce_listings pl JOIN locations l ON l.id = pl.location_id WHERE pl.status = "active" ORDER BY pl.created_at DESC LIMIT 4');
$prices = fetch_all('SELECT mp.average_price, mp.unit, pc.name AS category_name FROM market_prices mp JOIN produce_categories pc ON pc.id = mp.category_id ORDER BY mp.price_date DESC, mp.created_at DESC LIMIT 4');
$facilities = fetch_all('SELECT sf.id,sf.name,sf.available_capacity_kg,sf.price_per_kg_day,l.district FROM storage_facilities sf JOIN locations l ON l.id=sf.location_id WHERE sf.status="active" ORDER BY sf.available_capacity_kg DESC LIMIT 3');
$metrics = [
    'listings' => (int) (fetch_one('SELECT COUNT(*) AS count FROM produce_listings WHERE status = "active"')['count'] ?? 0),
    'facilities' => (int) (fetch_one('SELECT COUNT(*) AS count FROM storage_facilities WHERE status = "active"')['count'] ?? 0),
    'providers' => (int) (fetch_one('SELECT COUNT(*) AS count FROM transport_providers tp JOIN users u ON u.id = tp.user_id WHERE u.status = "active"')['count'] ?? 0),
];
require __DIR__ . '/includes/header.php';
?>
<main class="desk-home"><div class="desk-wrap">
    <section class="desk-hero"><div><h1>Connect. Store. Sell. Grow.</h1><p class="desk-hero-copy">A digital marketplace connecting Quetta's farmers with buyers, cold storage, and reliable transportation.</p><div class="desk-hero-actions"><a class="button button-primary" href="<?= e(app_url('marketplace/index.php')) ?>">Explore Marketplace</a><a class="button button-outline" href="<?= e(app_url('auth/register.php?role=farmer')) ?>">Join as a Farmer</a></div><div class="desk-signal-row"><article><strong><?= $metrics['listings'] ?></strong><span>active listings</span></article><article><strong><?= $metrics['facilities'] ?></strong><span>storage options</span></article><article><strong><?= $metrics['providers'] ?></strong><span>transport providers</span></article></div></div><aside class="desk-hero-board"><div class="desk-board-image"></div><div class="desk-board-content"><div><strong>One platform for everything after harvest.</strong></div><small>Quetta, Balochistan</small></div></aside></section>
    <section class="desk-section"><div class="desk-section-head"><div><h2>Choose a task</h2></div><p>Start with the part of your work that needs attention today.</p></div><div class="desk-task-grid"><article class="desk-task"><span class="desk-task-mark">1</span><h3>Find produce</h3><p>Compare origin, grade, quantity and expected price.</p><a href="<?= e(app_url('marketplace/index.php')) ?>">Browse produce</a></article><article class="desk-task"><span class="desk-task-mark">2</span><h3>Find storage</h3><p>Check capacity, location and produce compatibility.</p><a href="<?= e(app_url('storage/index.php')) ?>">Browse storage</a></article><article class="desk-task"><span class="desk-task-mark">3</span><h3>Plan transport</h3><p>Review vehicle capacity, routes and pickup dates.</p><a href="<?= e(app_url('transport/index.php')) ?>">Browse transport</a></article><article class="desk-task"><span class="desk-task-mark">4</span><h3>Check price records</h3><p>Use approved local reference ranges for context.</p><a href="<?= e(app_url('market-prices.php')) ?>">View prices</a></article></div></section>
    <section class="desk-section"><div class="desk-section-head"><div><h2>Latest produce listings</h2></div><a class="button button-outline" href="<?= e(app_url('marketplace/index.php')) ?>">View all listings</a></div><div class="desk-market"><div class="ledger"><div class="ledger-row ledger-head"><span>Produce and origin</span><span>Grade</span><span>Available</span><span>Expected price</span><span></span></div><?php if ($latestListings === []): ?><div class="ledger-row"><div class="commodity"><div class="commodity-mark"></div><div><h3>No produce listings yet</h3><p>New listings appear here when growers publish them.</p></div></div><span></span><span></span><span></span><span></span></div><?php else: foreach ($latestListings as $index => $listing): ?><div class="ledger-row"><div class="commodity"><div class="commodity-mark <?= ['', 'grape', 'apricot', 'pomegranate'][$index % 4] ?>"></div><div><h3><?= e($listing['title']) ?></h3><p><?= e($listing['district']) ?>, Balochistan</p></div></div><span><span class="badge">Grade <?= e($listing['grade']) ?></span></span><span><?= e((string) $listing['quantity_available']) ?> <?= e($listing['unit']) ?></span><span class="price">Rs. <?= number_format((float) $listing['expected_price'], 0) ?>/<?= e($listing['unit']) ?></span><span class="list-action"><a class="button button-quiet" href="<?= e(app_url('marketplace/listing.php?id=' . (int) $listing['id'])) ?>">View</a></span></div><?php endforeach; endif; ?></div></div></section>
    <section class="desk-section"><div class="desk-section-head"><div><h2>Available cold storage</h2><p>Compare verified capacity and current listed rates.</p></div><a class="button button-outline" href="<?= e(app_url('storage/index.php')) ?>">View storage</a></div><div class="desk-task-grid"><?php if($facilities===[]):?><article class="desk-task"><h3>No active facilities yet</h3><p>Provider capacity appears here after publication.</p></article><?php else:foreach($facilities as $facility):?><article class="desk-task"><h3><?= e($facility['name']) ?></h3><p><?= e($facility['district']) ?> · <?= number_format((float)$facility['available_capacity_kg'],0) ?> kg available</p><strong>Rs. <?= number_format((float)$facility['price_per_kg_day'],2) ?>/kg/day</strong></article><?php endforeach;endif;?></div></section>
    <section class="desk-section"><div class="desk-section-head"><div><h2>Built for both sides of local trade</h2><p>Clear terms, accountable records, and fewer disconnected handovers.</p></div></div><div class="desk-support-grid"><article class="desk-support-card"><h3>For farmers</h3><p>Publish harvest supply, negotiate offers, track sales, reserve storage, arrange transport, and keep transaction history in one workspace.</p></article><article class="desk-support-card"><h3>For buyers</h3><p>Filter real availability, compare grade and price, save listings, negotiate terms, place orders, and follow delivery progress.</p></article></div></section>
    <section class="desk-section"><div class="desk-support-grid"><article class="desk-support-card"><h3>Need help inside your account?</h3><p>Signed-in users can record a local support request. It stays in the relevant workspace and is not sent through an external channel.</p><a class="button" href="<?= e(app_url('support.php')) ?>">Open in-app support</a></article><article class="desk-price-card"><h3>Recent price records</h3><?php if ($prices === []): ?><div class="desk-price-line"><span>Market prices</span><strong>Awaiting records</strong></div><?php else: foreach ($prices as $price): ?><div class="desk-price-line"><span><?= e($price['category_name']) ?></span><strong>Rs. <?= number_format((float) $price['average_price'], 0) ?>/<?= e($price['unit']) ?></strong></div><?php endforeach; endif; ?></article></div></section>
    <section class="desk-section"><div class="desk-cta"><div><h2>Ready to manage local trade work?</h2><p>Choose your role and open the relevant workspace.</p></div><a class="button button-primary" href="<?= e(app_url('auth/register.php')) ?>">Create account</a></div></section>
</div></main>
<?php require __DIR__ . '/includes/footer.php'; ?>
