<?php
/** Orchard Ledger price intelligence: data-led reference ranges, not a prediction or a transaction quote. */
declare(strict_types=1);
require_once __DIR__ . '/includes/bootstrap.php';
require_once __DIR__ . '/includes/prices.php';
$categoryId=filter_input(INPUT_GET,'category_id',FILTER_VALIDATE_INT,['options'=>['min_range'=>1]])?:null;$categories=fetch_all('SELECT id,name FROM produce_categories WHERE is_active=1 ORDER BY name');$prices=find_market_prices($categoryId);$trendSql='SELECT mp.price_date,pc.name,mp.average_price,mp.unit,l.district FROM market_prices mp JOIN produce_categories pc ON pc.id=mp.category_id JOIN locations l ON l.id=mp.location_id'.($categoryId?' WHERE mp.category_id=:category':'').' ORDER BY mp.price_date DESC,mp.id DESC LIMIT 18';$trends=fetch_all($trendSql,$categoryId?['category'=>$categoryId]:[]);$pageTitle='Market Prices';
require __DIR__ . '/includes/header.php';
?>
<section class="page-intro price-intro"><div class="site-container"><span class="eyebrow" style="color:var(--clay)">Market intelligence</span><h1>Use recorded local ranges as trade context.</h1><p>These entries are recorded by authorized platform administrators from named local sources. They are reference information—not a guaranteed trade price, an offer, or financial advice.</p></div></section>
<section class="section price-register-section"><div class="site-container"><div class="price-register-lead"><div><p class="desk-kicker">Recorded market prices</p><h2>Reference records for the next trade conversation.</h2><p>Start with the recorded range and its named source, then confirm the actual quantity, grade, timing, and terms in the relevant marketplace record.</p></div><div class="market-toolbar"><form data-price-filter data-endpoint="<?= e(app_url('ajax/prices/search.php')) ?>" class="form-field" style="min-width:260px"><label for="category_id">View a product</label><select id="category_id" name="category_id"><option value="">All recorded products</option><?php foreach($categories as $category):?><option value="<?= (int)$category['id'] ?>" <?= $categoryId===(int)$category['id']?'selected':'' ?>><?= e($category['name']) ?></option><?php endforeach;?></select></form><p class="muted" data-price-feedback><?= count($prices) ?> recorded price entr<?= count($prices)===1?'y':'ies' ?> shown.</p></div></div><div class="price-register-layout"><div class="price-register-table"><div class="data-table-wrap"><table class="data-table"><thead><tr><th>Product</th><th>Market</th><th>Minimum</th><th>Maximum</th><th>Average</th><th>Recorded</th><th>Source</th></tr></thead><tbody data-price-results><?= market_price_rows($prices) ?></tbody></table></div></div><aside class="price-reference-note"><p class="desk-kicker">Using this record</p><h2>Reference, not a quote.</h2><p>Use the range and its named source to frame a conversation. Actual offers, order terms, grade checks, and logistics costs are recorded separately in the platform workflow.</p><div class="price-reference-points"><span>Administrator-entered</span><span>Named local source</span><span>Update the trade record separately</span></div><a class="button button-primary" href="<?= e(app_url('marketplace/index.php')) ?>">Browse available produce</a></aside></div></div></section>
<section class="section"><div class="site-container"><div class="section-heading"><div><h2>Recorded price trend</h2><p>Recent average prices in date order; use the product filter above to focus this history.</p></div></div><div class="data-table-wrap"><table class="data-table"><thead><tr><th>Date</th><th>Product</th><th>Market</th><th>Average</th></tr></thead><tbody><?php if($trends===[]):?><tr><td colspan="4">No price history has been recorded yet.</td></tr><?php else:foreach($trends as $trend):?><tr><td><?= e(date('j M Y',strtotime($trend['price_date']))) ?></td><td><?= e($trend['name']) ?></td><td><?= e($trend['district']) ?></td><td><strong>Rs. <?= number_format((float)$trend['average_price'],2) ?>/<?= e($trend['unit']) ?></strong></td></tr><?php endforeach;endif;?></tbody></table></div></div></section>
<?php require __DIR__ . '/includes/footer.php'; ?>
