<?php
declare(strict_types=1);
require_once __DIR__.'/includes/bootstrap.php';require_once __DIR__.'/includes/workspace.php';$user=require_role(['farmer','storage_provider','transport_provider']);
function media_entities(array $user): array{return match($user['role_slug']){'farmer'=>fetch_all('SELECT id,title AS label FROM produce_listings WHERE farmer_id=:user ORDER BY created_at DESC',['user'=>$user['id']]),'storage_provider'=>fetch_all('SELECT sf.id,sf.name AS label FROM storage_facilities sf JOIN storage_providers sp ON sp.id=sf.provider_id WHERE sp.user_id=:user ORDER BY sf.created_at DESC',['user'=>$user['id']]),'transport_provider'=>fetch_all('SELECT v.id,CONCAT(v.vehicle_type," · ",v.registration_number) AS label FROM vehicles v JOIN transport_providers tp ON tp.id=v.provider_id WHERE tp.user_id=:user ORDER BY v.created_at DESC',['user'=>$user['id']]),default=>[]};}
function media_owned_entity(array $user,int $id):?array{return match($user['role_slug']){'farmer'=>fetch_one('SELECT id,title AS label FROM produce_listings WHERE id=:id AND farmer_id=:user',['id'=>$id,'user'=>$user['id']]),'storage_provider'=>fetch_one('SELECT sf.id,sf.name AS label FROM storage_facilities sf JOIN storage_providers sp ON sp.id=sf.provider_id WHERE sf.id=:id AND sp.user_id=:user',['id'=>$id,'user'=>$user['id']]),'transport_provider'=>fetch_one('SELECT v.id,CONCAT(v.vehicle_type," · ",v.registration_number) AS label FROM vehicles v JOIN transport_providers tp ON tp.id=v.provider_id WHERE v.id=:id AND tp.user_id=:user',['id'=>$id,'user'=>$user['id']]),default=>null};}
function save_market_image(array $file):string
{
    if(($file['error']??UPLOAD_ERR_NO_FILE)!==UPLOAD_ERR_OK)throw new RuntimeException('Choose an image to upload.');
    if((int)$file['size']<1||(int)$file['size']>MAX_UPLOAD_BYTES)throw new RuntimeException('Images must be no larger than 5 MB.');
    $mime=(new finfo(FILEINFO_MIME_TYPE))->file($file['tmp_name']);$types=['image/jpeg'=>'jpg','image/png'=>'png','image/webp'=>'webp'];$info=getimagesize($file['tmp_name']);
    if(!isset($types[$mime])||$info===false)throw new RuntimeException('Upload a valid JPEG, PNG, or WebP image.');
    $directory=UPLOAD_STORAGE_PATH.'/market-media';if(!is_dir($directory)&&!mkdir($directory,0755,true))throw new RuntimeException('The media directory is unavailable.');
    $name=bin2hex(random_bytes(16)).'.'.$types[$mime];$target=$directory.'/'.$name;$saved=false;
    if(extension_loaded('gd')){
        $source=match($mime){'image/jpeg'=>@imagecreatefromjpeg($file['tmp_name']),'image/png'=>@imagecreatefrompng($file['tmp_name']),'image/webp'=>function_exists('imagecreatefromwebp')?@imagecreatefromwebp($file['tmp_name']):false};
        if($source!==false){$width=(int)$info[0];$height=(int)$info[1];$scale=min(1,1600/max($width,$height));$newWidth=max(1,(int)round($width*$scale));$newHeight=max(1,(int)round($height*$scale));$canvas=imagecreatetruecolor($newWidth,$newHeight);if($mime!=='image/jpeg'){imagealphablending($canvas,false);imagesavealpha($canvas,true);}$saved=imagecopyresampled($canvas,$source,0,0,0,0,$newWidth,$newHeight,$width,$height)&&match($mime){'image/jpeg'=>imagejpeg($canvas,$target,84),'image/png'=>imagepng($canvas,$target,7),'image/webp'=>imagewebp($canvas,$target,84)};imagedestroy($canvas);imagedestroy($source);}
    }
    if(!$saved&&!move_uploaded_file($file['tmp_name'],$target))throw new RuntimeException('The image could not be stored.');
    return 'uploads/market-media/'.$name;
}
if($_SERVER['REQUEST_METHOD']==='POST'){verify_csrf();try{$entityId=(int)($_POST['entity_id']??0);$entity=media_owned_entity($user,$entityId);if($entity===null)throw new RuntimeException('That record is not owned by this account.');$action=normalize_text($_POST['media_action']??'upload',20);if($action==='upload'){$path=save_market_image($_FILES['image']??[]);$alt=normalize_text($_POST['alt_text']??'',180);if($user['role_slug']==='farmer')db()->prepare('INSERT INTO produce_images(listing_id,file_path,alt_text,is_primary) VALUES(:id,:path,:alt,NOT EXISTS(SELECT 1 FROM produce_images existing WHERE existing.listing_id=:id_check))')->execute(['id'=>$entityId,'path'=>$path,'alt'=>$alt?:$entity['label'],'id_check'=>$entityId]);elseif($user['role_slug']==='storage_provider')db()->prepare('INSERT INTO storage_facility_images(facility_id,file_path,alt_text,is_primary) VALUES(:id,:path,:alt,NOT EXISTS(SELECT 1 FROM storage_facility_images existing WHERE existing.facility_id=:id_check))')->execute(['id'=>$entityId,'path'=>$path,'alt'=>$alt?:$entity['label'],'id_check'=>$entityId]);else execute_query('UPDATE vehicles SET image_path=:path WHERE id=:id',['path'=>$path,'id'=>$entityId]);audit_log((int)$user['id'],'market_media_uploaded',$user['role_slug'],$entityId,['mime'=>'validated_image']);flash('success','Image uploaded securely.');}else throw new RuntimeException('That media action is unavailable.');}catch(Throwable $e){flash('error',$e->getMessage());}redirect('media.php');}
$entities=media_entities($user);$images=match($user['role_slug']){'farmer'=>fetch_all('SELECT pi.id,pi.listing_id AS entity_id,pi.file_path,pi.alt_text,pl.title AS label FROM produce_images pi JOIN produce_listings pl ON pl.id=pi.listing_id WHERE pl.farmer_id=:user ORDER BY pi.created_at DESC',['user'=>$user['id']]),'storage_provider'=>fetch_all('SELECT fi.id,fi.facility_id AS entity_id,fi.file_path,fi.alt_text,sf.name AS label FROM storage_facility_images fi JOIN storage_facilities sf ON sf.id=fi.facility_id JOIN storage_providers sp ON sp.id=sf.provider_id WHERE sp.user_id=:user ORDER BY fi.created_at DESC',['user'=>$user['id']]),'transport_provider'=>fetch_all('SELECT v.id,v.id AS entity_id,v.image_path AS file_path,CONCAT(v.vehicle_type," ",v.registration_number) AS alt_text,v.registration_number AS label FROM vehicles v JOIN transport_providers tp ON tp.id=v.provider_id WHERE tp.user_id=:user AND v.image_path IS NOT NULL ORDER BY v.updated_at DESC',['user'=>$user['id']]),default=>[]};workspace_open('Marketplace media','media');
?>
<section class="workspace-section"><div class="workspace-section-header"><div><h2>Upload owned record images</h2><p>JPEG, PNG, or WebP only; maximum 5 MB. File content is inspected and random non-executable names are used.</p></div></div><form method="post" enctype="multipart/form-data" class="form-grid"><input type="hidden" name="_csrf" value="<?= e(csrf_token()) ?>"><input type="hidden" name="media_action" value="upload"><label>Record<select name="entity_id" required><option value="">Choose record</option><?php foreach($entities as $entity):?><option value="<?= (int)$entity['id'] ?>"><?= e($entity['label']) ?></option><?php endforeach;?></select></label><label>Image<input type="file" name="image" accept="image/jpeg,image/png,image/webp" required></label><label>Alternative text<input name="alt_text" maxlength="180" required></label><button class="button button-primary" type="submit">Upload image</button></form></section><section class="workspace-section"><div class="workspace-section-header"><div><h2>Current media</h2><p>Images attached to this account's records.</p></div></div><div class="media-grid"><?php if($images===[]):?><div class="empty-state"><h3>No images uploaded yet</h3><p>Choose an owned record above to add its first image.</p></div><?php else:foreach($images as $image):?><figure><img loading="lazy" src="<?= e(app_url($image['file_path'])) ?>" alt="<?= e($image['alt_text']) ?>"><figcaption><?= e($image['label']) ?></figcaption></figure><?php endforeach;endif;?></div></section>
<?php workspace_close(); ?>
