<?php
declare(strict_types=1);
require_once __DIR__ . '/includes/bootstrap.php';
require_once __DIR__ . '/includes/workspace.php';
$user=require_role(['farmer','buyer']);
if($_SERVER['REQUEST_METHOD']==='POST'){
    verify_csrf();
    try{$id=send_commercial_message($user,(int)($_POST['listing_id']??0),(int)($_POST['order_id']??0),(string)($_POST['body']??''),(int)($_POST['recipient_id']??0));if(is_ajax_request())json_response(true,'Message sent.',['message_id'=>$id,'redirect'=>app_url('messages.php?'.((int)($_POST['order_id']??0)>0?'order_id='.(int)$_POST['order_id']:'listing_id='.(int)$_POST['listing_id'].'&peer_id='.(int)$_POST['recipient_id']))]);flash('success','Message sent.');}catch(Throwable $e){if(is_ajax_request())json_response(false,$e->getMessage(),[],422);flash('error',$e->getMessage());}redirect('messages.php');
}
$orderId=filter_input(INPUT_GET,'order_id',FILTER_VALIDATE_INT,['options'=>['min_range'=>1]])?:0;$listingId=filter_input(INPUT_GET,'listing_id',FILTER_VALIDATE_INT,['options'=>['min_range'=>1]])?:0;$peerId=filter_input(INPUT_GET,'peer_id',FILTER_VALIDATE_INT,['options'=>['min_range'=>1]])?:0;
$contexts=fetch_all('SELECT DISTINCT o.id AS order_id,NULL AS listing_id,IF(o.buyer_id=:u1,o.farmer_id,o.buyer_id) AS peer_id,CONCAT("Order ",o.reference_code) AS label,o.updated_at FROM orders o WHERE o.buyer_id=:u2 OR o.farmer_id=:u3 UNION SELECT NULL,pl.id,IF(f.buyer_id=:u4,f.farmer_id,f.buyer_id),CONCAT(pl.title," · ",peer.full_name),f.updated_at FROM offers f JOIN produce_listings pl ON pl.id=f.listing_id JOIN users peer ON peer.id=IF(f.buyer_id=:u5,f.farmer_id,f.buyer_id) WHERE f.buyer_id=:u6 OR f.farmer_id=:u7 ORDER BY updated_at DESC',['u1'=>$user['id'],'u2'=>$user['id'],'u3'=>$user['id'],'u4'=>$user['id'],'u5'=>$user['id'],'u6'=>$user['id'],'u7'=>$user['id']]);
$thread=[];$context=null;if($orderId||$listingId){try{$context=commercial_context($listingId,$orderId,$user,$peerId);$where=$orderId?'m.order_id=:context':'m.listing_id=:context AND ((m.sender_id=:sender_user AND m.recipient_id=:recipient_peer) OR (m.sender_id=:sender_peer AND m.recipient_id=:recipient_user))';$params=['context'=>$orderId?:$listingId];if(!$orderId)$params+=['sender_user'=>$user['id'],'recipient_user'=>$user['id'],'recipient_peer'=>$context['recipient_id'],'sender_peer'=>$context['recipient_id']];$thread=fetch_all('SELECT m.*,u.full_name FROM messages m JOIN users u ON u.id=m.sender_id WHERE '.$where.' ORDER BY m.created_at,m.id',$params);execute_query('UPDATE messages SET read_at=NOW() WHERE '.($orderId?'order_id=:context':'listing_id=:context').' AND recipient_id=:user AND sender_id=:peer AND read_at IS NULL',['context'=>$orderId?:$listingId,'user'=>$user['id'],'peer'=>$context['recipient_id']]);}catch(Throwable $e){flash('error',$e->getMessage());}}
workspace_open('Commercial messages','messages');
?>
<section class="workspace-section message-layout"><aside><h2>Conversations</h2><?php if($contexts===[]): ?><p class="muted">No eligible listing or order conversations yet.</p><?php else: foreach($contexts as $item): $url=$item['order_id']?'order_id='.(int)$item['order_id']:'listing_id='.(int)$item['listing_id'].'&peer_id='.(int)$item['peer_id']; ?><a class="message-context <?= (($orderId&&(int)$item['order_id']===$orderId)||($listingId&&(int)$item['listing_id']===$listingId&&(int)$item['peer_id']===$peerId))?'is-active':'' ?>" href="<?= e(app_url('messages.php?'.$url)) ?>"><?= e($item['label']) ?></a><?php endforeach; endif; ?></aside><div><div class="workspace-section-header"><div><h2><?= e($context['label']??'Choose a conversation') ?></h2><p>Simple in-app messages only; no external delivery or public contact details.</p></div></div><?php if($context): ?><div class="message-thread"><?php if($thread===[]): ?><p class="muted">No messages in this conversation yet.</p><?php else:foreach($thread as $message):?><article class="support-message <?= (int)$message['sender_id']===(int)$user['id']?'is-own':'' ?>"><strong><?= e($message['full_name']) ?></strong><p><?= nl2br(e($message['body'])) ?></p><time><?= e(date('j M Y H:i',strtotime($message['created_at']))) ?></time></article><?php endforeach;endif;?></div><form method="post" action="<?= e(app_url('messages.php')) ?>" data-ajax-form class="form-grid"><input type="hidden" name="_csrf" value="<?= e(csrf_token()) ?>"><input type="hidden" name="listing_id" value="<?= (int)($context['listing_id']??0) ?>"><input type="hidden" name="order_id" value="<?= (int)($context['order_id']??0) ?>"><input type="hidden" name="recipient_id" value="<?= (int)$context['recipient_id'] ?>"><label>Message<textarea name="body" maxlength="2000" required rows="4"></textarea></label><button class="button button-primary" type="submit">Send message</button><span data-form-feedback></span></form><?php endif; ?></div></section>
<?php workspace_close(); ?>
