/** Orchard Ledger information pages: plain-language product context without claims or simulated support actions. */
import { ArrowRight, CheckCircle2, CircleHelp, Mail, ShieldCheck } from "lucide-react";
import { Link } from "wouter";
import { PageHero, PreviewLayout } from "@/components/PreviewLayout";

const content = {
  about: { eyebrow: "About Quetta AgriLink", title: <>Practical infrastructure for the work <i>after harvest.</i></>, copy: "Quetta AgriLink connects growers, buyers, storage operators, and transport providers around a clear view of produce, capacity, movement, and status.", heading: "One platform for every operational handover.", text: "The agricultural supply chain needs a clearer handover between availability, commercial intent, temperature control, and delivery. The platform makes these steps visible as one commercial record.", items: ["Trade-ready supply information", "Specific booking and transport requests", "Role-scoped operational workspaces"] },
  how: { eyebrow: "How it works", title: <>Turn the harvest handover into a <i>connected workflow.</i></>, copy: "Each participant provides information that makes the next operation more specific: supply, terms, capacity, transport, and delivery status.", heading: "Built for the work that follows harvest.", text: "The preview shows the route map for a practical trading workflow. The PHP/XAMPP package provides the secured role checks and database records behind these flows.", items: ["Farmer listings and buyer offers", "Storage requests with capacity checks", "Transport milestones from acceptance to delivery"] },
  contact: { eyebrow: "Contact", title: <>Set up an owned support channel <i>before launch.</i></>, copy: "This development build avoids simulated customer support forms. Configure a verified support email or authenticated helpdesk before use with live customers.", heading: "A candid development contact route.", text: "The source package includes public contact context while keeping the next communication step explicit. Production support needs an owned channel and a documented privacy process.", items: ["Verified operating email", "Customer-data policy", "Authenticated support workflow"] },
};
export default function Information({ page }: { page: keyof typeof content }) { const item = content[page]; const Icon = page === "contact" ? Mail : page === "how" ? CircleHelp : ShieldCheck; return <PreviewLayout><PageHero eyebrow={item.eyebrow} title={item.title} copy={item.copy} /><section className="info-page"><div className="info-symbol"><Icon size={43} /></div><div><p className="eyebrow clay"><span /> Platform context</p><h2>{item.heading}</h2><p>{item.text}</p><ul>{item.items.map((entry) => <li key={entry}><CheckCircle2 size={17} />{entry}</li>)}</ul><Link className="button button-canopy" href="/marketplace">Explore marketplace <ArrowRight size={16} /></Link></div></section></PreviewLayout>; }
