/** Orchard Ledger logistics previews: capacity, refrigeration, and vehicle facts precede any request action. */
import { ArrowRight, Check, Clock3, MapPin, Snowflake, ThermometerSnowflake, Truck } from "lucide-react";
import { Link } from "wouter";
import { PageHero, PreviewLayout } from "@/components/PreviewLayout";

const storageFacts = [["Available capacity", "76,000 kg"], ["Storage type", "Cold room"], ["Daily price", "Rs. 3.50/kg"], ["Compatible", "Apple, grape, apricot"]];
const transportFacts = [["Available fleet", "3 vehicles"], ["Maximum capacity", "10,000 kg"], ["Temperature control", "Refrigerated"], ["Service coverage", "Quetta & Balochistan"]];

function ServiceRequest({ kind }: { kind: "storage" | "transport" }) {
  const storage = kind === "storage";
  const Icon = storage ? Snowflake : Truck;
  const facts = storage ? storageFacts : transportFacts;
  return <PreviewLayout><PageHero eyebrow={storage ? "Cold-storage exchange" : "Transport exchange"} title={storage ? <>Reserve capacity that keeps a harvest <i>market-ready.</i></> : <>Match the crop to a <i>capable vehicle.</i></>} copy={storage ? "Review storage type, compatible produce, available capacity, and daily pricing before you request space." : "Compare fleet capability, capacity, refrigeration and service coverage before you request a pickup."} image={kind} /><section className="service-page"><div className="service-page-main"><div className="service-page-head"><div><p className="eyebrow clay"><span /> Available provider</p><h2>{storage ? "Quetta Valley Cold Store" : "Baloch Route Transport"}</h2><p><MapPin size={15} /> Quetta, Balochistan</p></div><span className="provider-status"><Check size={14} /> Available to review requests</span></div><div className="service-facts">{facts.map(([label, value]) => <div key={label}><small>{label}</small><strong>{value}</strong></div>)}</div><div className="service-detail"><Icon size={28} /><div><h3>{storage ? "Terms visible before the booking." : "Operational detail before dispatch."}</h3><p>{storage ? "A booking remains requested until the facility provider checks dates, capacity, and compatible produce. Each status change is recorded in the provider workspace." : "A provider-owned request can move through acceptance, driver assignment, pickup, transit and delivery with each milestone documented."}</p></div></div></div><aside className="request-card"><p className="eyebrow clay"><span /> {storage ? "Booking request" : "Pickup request"}</p><h3>{storage ? "Plan cold storage" : "Plan a produce pickup"}</h3><p>This visible preview represents the request flow. The secure PHP application validates account role, ownership, quantity, and capacity before saving a real request.</p><div className="request-fields"><span>Produce <b>{storage ? "Pishin Red Apples" : "Mastung Seedless Grapes"}</b></span><span>{storage ? "Requested capacity" : "Pickup quantity"}<b>{storage ? "2,400 kg" : "1,150 kg"}</b></span><span>{storage ? "Proposed dates" : "Pickup date"}<b>{storage ? "12–19 Sep 2026" : "12 Sep 2026"}</b></span></div><Link className="button button-canopy button-large" href="/farmer">Open farmer workspace <ArrowRight size={17} /></Link><p className="request-note"><Clock3 size={13} /> No capacity or vehicle is committed from this preview.</p></aside></section></PreviewLayout>;
}

export function StoragePage() { return <ServiceRequest kind="storage" />; }
export function TransportPage() { return <ServiceRequest kind="transport" />; }
