/** Market Desk sign-up: role-first onboarding helps a new user understand which workspace they will receive. */
import { type FormEvent, useState } from "react";
import { ArrowRight, CheckCircle2, ShoppingBasket, Sprout, Truck, Warehouse } from "lucide-react";
import { useLocation } from "wouter";
import { Brand } from "@/components/PreviewLayout";
import { startSession, type AccountRole } from "@/lib/operations";

const destinations: Record<AccountRole, string> = { farmer: "/farmer", buyer: "/buyer", storage: "/storage-provider", transport: "/transport-provider", admin: "/admin" };
const roles = [{ value: "farmer" as const, label: "Farmer", detail: "Publish harvest and manage offers.", icon: Sprout }, { value: "buyer" as const, label: "Buyer", detail: "Compare supply and manage offers.", icon: ShoppingBasket }, { value: "storage" as const, label: "Storage provider", detail: "Manage capacity and bookings.", icon: Warehouse }, { value: "transport" as const, label: "Transport provider", detail: "Manage vehicles and delivery requests.", icon: Truck }];
export default function SignUp() { const [, setLocation] = useLocation(); const [role, setRole] = useState<AccountRole>("farmer"); const [name, setName] = useState(""); const [created, setCreated] = useState(false); const submit = (event: FormEvent<HTMLFormElement>) => { event.preventDefault(); startSession(role, name.trim() ? `${name.trim().replaceAll(" ", ".").toLowerCase()}@quettaagrilink.pk` : "new.account@quettaagrilink.pk"); setCreated(true); window.setTimeout(() => setLocation(destinations[role]), 500); }; return <div className="market-desk-auth"><header><Brand /><a href="/sign-in">Already have an account? Sign in</a></header><main className="desk-auth-layout"><section className="desk-auth-intro"><p className="desk-kicker">Create an account</p><h1>Start with the role you have today.</h1><p>You can complete your operational profile later. First, choose the work you want to manage and create an account for that role.</p><div className="desk-auth-points"><div><CheckCircle2 size={19} /><span><strong>Simple start</strong>Add basic account details now; operational records come once your workspace opens.</span></div><div><CheckCircle2 size={19} /><span><strong>Built for your work</strong>Your workspace keeps producing, buying, capacity, or delivery tasks separate and clear.</span></div></div></section><section className="desk-auth-card"><p className="desk-kicker">Account details</p><h2>Choose your workspace</h2><p>Select the role that best describes your work in the post-harvest chain.</p><form onSubmit={submit}><label>Full name<input value={name} onChange={(event) => setName(event.target.value)} placeholder="Your full name" required /></label><label>Account role</label><div className="desk-role-choice">{roles.map(({ value, label, icon: Icon }) => <button type="button" className={role === value ? "active" : ""} onClick={() => setRole(value)} key={value}><Icon size={15} />{label}</button>)}</div><p className="desk-preview-note">{roles.find((item) => item.value === role)?.detail}</p><button className="button button-canopy button-large" type="submit">Create {roles.find((item) => item.value === role)?.label} account <ArrowRight size={17} /></button></form>{created && <div className="entry-confirm"><CheckCircle2 size={17} /><span>Your workspace is ready to open.</span></div>}<div className="desk-auth-footer"><span>Already registered?</span><a href="/sign-in">Sign in instead</a></div></section></main></div>; }
