<?php
/** Market Desk profile page: signed-in accounts update their own contact and role-specific commercial details through validated, auditable PHP forms. */
declare(strict_types=1);
require_once __DIR__ . '/../includes/bootstrap.php';
require_once __DIR__ . '/../includes/workspace.php';

$user = require_login();
$contactErrors = [];
$roleErrors = [];
$roleValues = [];
if ($_SERVER['REQUEST_METHOD'] === 'POST') {
    verify_csrf();
    $action = normalize_text($_POST['profile_action'] ?? 'contact', 40);
    if ($action === 'farmer_business') {
        [$success, $message, $meta] = $user['role_slug'] === 'farmer' ? update_farmer_business_profile((int) $user['id'], $_POST) : [false, 'This profile section is not available for your account.', []];
        $roleErrors = $meta['errors'] ?? [];
        $roleValues = $meta['values'] ?? [];
    } elseif ($action === 'buyer_business') {
        [$success, $message, $meta] = $user['role_slug'] === 'buyer' ? update_buyer_business_profile((int) $user['id'], $_POST) : [false, 'This profile section is not available for your account.', []];
        $roleErrors = $meta['errors'] ?? [];
        $roleValues = $meta['values'] ?? [];
    } else {
        [$success, $message, $meta] = update_account_profile((int) $user['id'], $_POST);
        $contactErrors = $meta['errors'] ?? [];
    }
    if ($success) {
        flash('success', $message);
        redirect('account/profile.php');
    }
    flash('error', $message);
}
$user = current_user() ?? $user;
$contactVerification = account_contact_verification((int) $user['id']);
$locations = in_array($user['role_slug'], ['farmer', 'buyer'], true) ? role_profile_locations() : [];
$roleProfile = role_business_profile((int) $user['id'], $user['role_slug']) ?? [];
$roleForm = $roleValues + $roleProfile;
$locationLabel = static fn (array $location): string => implode(' · ', array_filter([$location['district'] ?? '', $location['tehsil'] ?? '', $location['area'] ?? '']));
workspace_open('My profile', 'profile');
?>
<section class="workspace-section profile-section"><div class="workspace-section-header"><div><h2>Account details</h2><p>Keep your contact details current. Changes are recorded in your account audit trail.</p></div></div><div class="profile-contact-status"><div><span>Local contact review</span><strong>Email: <?= $contactVerification !== null && $contactVerification['verified_email_at'] !== null ? 'reviewed' : 'not reviewed' ?></strong><strong>Phone: <?= $contactVerification !== null && $contactVerification['verified_phone_at'] !== null ? 'reviewed' : 'not reviewed' ?></strong></div><p><?php if ($contactVerification !== null && $contactVerification['updated_at'] !== null): ?>An administrator last recorded a local review on <?= e(date('j M Y', strtotime((string) $contactVerification['updated_at']))) ?> using <?= e(contact_review_reason_label($contactVerification['review_reason_code'] ?? null)) ?>. Updating an email address or phone number clears its prior review status.<?php else: ?>Contact review is recorded by an administrator using the current account details. No automated email or phone verification is claimed.<?php endif; ?></p></div><form method="post" class="form-grid profile-form" novalidate><input type="hidden" name="_csrf" value="<?= e(csrf_token()) ?>"><input type="hidden" name="profile_action" value="contact"><div class="form-field"><label for="full_name">Full name</label><input id="full_name" name="full_name" value="<?= e($user['full_name']) ?>" autocomplete="name" required><?php if (isset($contactErrors['full_name'])): ?><small class="field-error"><?= e($contactErrors['full_name']) ?></small><?php endif; ?></div><div class="form-field"><label for="email">Email address</label><input id="email" name="email" type="email" value="<?= e($user['email']) ?>" autocomplete="email" required><?php if (isset($contactErrors['email'])): ?><small class="field-error"><?= e($contactErrors['email']) ?></small><?php endif; ?></div><div class="form-field"><label for="phone">Contact number</label><input id="phone" name="phone" value="<?= e($user['phone']) ?>" autocomplete="tel" required><?php if (isset($contactErrors['phone'])): ?><small class="field-error"><?= e($contactErrors['phone']) ?></small><?php endif; ?></div><div class="profile-role-note"><span>Your account role</span><strong><?= e($user['role_name']) ?></strong><p>Role changes are managed by an administrator to keep operational records accountable.</p></div><div class="form-actions"><a class="muted" href="<?= e(app_url(dashboard_path($user['role_slug']))) ?>">Return to dashboard</a><button class="button button-primary" type="submit">Save account details</button></div></form></section>
<?php if ($user['role_slug'] === 'farmer'): ?><section class="workspace-section profile-section"><div class="workspace-section-header"><div><h2>Farm and location</h2><p>Set the farm details buyers see alongside the produce you publish. Choose an existing service location so records remain consistent.</p></div></div><form method="post" class="form-grid profile-form" novalidate><input type="hidden" name="_csrf" value="<?= e(csrf_token()) ?>"><input type="hidden" name="profile_action" value="farmer_business"><div class="form-field"><label for="farm_name">Farm name</label><input id="farm_name" name="farm_name" maxlength="160" required value="<?= e((string) ($roleForm['farm_name'] ?? '')) ?>"><?php if (isset($roleErrors['farm_name'])): ?><small class="field-error"><?= e($roleErrors['farm_name']) ?></small><?php endif; ?></div><div class="form-field"><label for="farm_location_id">Farm location</label><select id="farm_location_id" name="farm_location_id" required><option value="">Choose a location</option><?php foreach ($locations as $location): ?><option value="<?= (int) $location['id'] ?>" <?= (int) ($roleForm['location_id'] ?? 0) === (int) $location['id'] ? 'selected' : '' ?>><?= e($locationLabel($location)) ?></option><?php endforeach; ?></select><?php if (isset($roleErrors['farm_location_id'])): ?><small class="field-error"><?= e($roleErrors['farm_location_id']) ?></small><?php endif; ?></div><div class="form-field"><label for="farm_size_acres">Farm size (acres)</label><input id="farm_size_acres" name="farm_size_acres" type="number" min="0.01" max="100000" step="0.01" value="<?= e((string) ($roleForm['farm_size_acres'] ?? '')) ?>"><?php if (isset($roleErrors['farm_size_acres'])): ?><small class="field-error"><?= e($roleErrors['farm_size_acres']) ?></small><?php endif; ?></div><div class="form-field"><label for="farm_bio">Farm details</label><textarea id="farm_bio" name="farm_bio" maxlength="1000" rows="4" placeholder="Produce, growing practices, or collection details buyers should know."><?= e((string) ($roleForm['bio'] ?? '')) ?></textarea></div><div class="form-actions"><button class="button button-primary" type="submit">Save farm details</button></div></form></section><?php endif; ?>
<?php if ($user['role_slug'] === 'buyer'): ?><section class="workspace-section profile-section"><div class="workspace-section-header"><div><h2>Business details</h2><p>Set the commercial information that accompanies your purchase offers. Your tax reference remains in this protected account profile.</p></div></div><form method="post" class="form-grid profile-form" novalidate><input type="hidden" name="_csrf" value="<?= e(csrf_token()) ?>"><input type="hidden" name="profile_action" value="buyer_business"><div class="form-field"><label for="business_name">Business name</label><input id="business_name" name="business_name" maxlength="160" required value="<?= e((string) ($roleForm['business_name'] ?? '')) ?>"><?php if (isset($roleErrors['business_name'])): ?><small class="field-error"><?= e($roleErrors['business_name']) ?></small><?php endif; ?></div><div class="form-field"><label for="business_type">Business type</label><input id="business_type" name="business_type" maxlength="100" required value="<?= e((string) ($roleForm['business_type'] ?? '')) ?>" placeholder="Wholesaler, retailer, processor, or exporter"><?php if (isset($roleErrors['business_type'])): ?><small class="field-error"><?= e($roleErrors['business_type']) ?></small><?php endif; ?></div><div class="form-field"><label for="business_location_id">Business location</label><select id="business_location_id" name="business_location_id" required><option value="">Choose a location</option><?php foreach ($locations as $location): ?><option value="<?= (int) $location['id'] ?>" <?= (int) ($roleForm['location_id'] ?? 0) === (int) $location['id'] ? 'selected' : '' ?>><?= e($locationLabel($location)) ?></option><?php endforeach; ?></select><?php if (isset($roleErrors['business_location_id'])): ?><small class="field-error"><?= e($roleErrors['business_location_id']) ?></small><?php endif; ?></div><div class="form-field"><label for="tax_reference">Tax reference <span class="muted">(optional)</span></label><input id="tax_reference" name="tax_reference" maxlength="80" value="<?= e((string) ($roleForm['tax_reference'] ?? '')) ?>" autocomplete="off"><?php if (isset($roleErrors['tax_reference'])): ?><small class="field-error"><?= e($roleErrors['tax_reference']) ?></small><?php endif; ?></div><div class="form-field"><label for="business_bio">Business details</label><textarea id="business_bio" name="business_bio" maxlength="1000" rows="4" placeholder="Purchase focus, handling needs, or regular trade information."><?= e((string) ($roleForm['bio'] ?? '')) ?></textarea></div><div class="form-actions"><button class="button button-primary" type="submit">Save business details</button></div></form></section><?php endif; ?>
<?php workspace_close(); ?>
