<?php
/** Orchard Ledger transport-provider dashboard: requests, capacity, and movement status form the essential dispatch view. */
declare(strict_types=1);
require_once __DIR__ . '/../includes/bootstrap.php';
require_once __DIR__ . '/../includes/workspace.php';
$user=require_role(['transport_provider']);$provider=fetch_one('SELECT id FROM transport_providers WHERE user_id=:user LIMIT 1',['user'=>$user['id']]);$vehicles=fetch_one('SELECT COUNT(*) AS count FROM vehicles WHERE provider_id=:provider AND status="available"',['provider'=>$provider['id']]);$pending=fetch_one('SELECT COUNT(*) AS count FROM transport_requests WHERE provider_id=:provider AND status="requested"',['provider'=>$provider['id']]);$active=fetch_one('SELECT COUNT(*) AS count FROM transport_requests WHERE provider_id=:provider AND status IN("accepted","driver_assigned","pickup_scheduled","picked_up","in_transit")',['provider'=>$provider['id']]);$delivered=fetch_one('SELECT COUNT(*) AS count FROM transport_requests WHERE provider_id=:provider AND status="delivered"',['provider'=>$provider['id']]);
workspace_open('Transport provider dashboard','dashboard');render_status_cards([['label'=>'Available vehicles','value'=>(int)$vehicles['count'],'detail'=>'ready in your listed fleet'],['label'=>'New requests','value'=>(int)$pending['count'],'detail'=>'awaiting a response'],['label'=>'Active trips','value'=>(int)$active['count'],'detail'=>'accepted through transit'],['label'=>'Delivered trips','value'=>(int)$delivered['count'],'detail'=>'recorded as delivered']]);$recent=fetch_all('SELECT tr.reference_code,tr.produce_description,tr.quantity_kg,tr.pickup_date,tr.status,u.full_name FROM transport_requests tr JOIN users u ON u.id=tr.farmer_id WHERE tr.provider_id=:provider ORDER BY tr.created_at DESC LIMIT 6',['provider'=>$provider['id']]);
?>
<section class="workspace-section"><div class="workspace-section-header"><div><h2>Transport requests</h2><p>Requests remain in a provider-scoped view until your team responds.</p></div></div><div class="data-table-wrap"><table class="data-table"><thead><tr><th>Reference</th><th>Farmer</th><th>Produce</th><th>Pickup</th><th>Status</th></tr></thead><tbody><?php if($recent===[]):?><tr><td colspan="5">No transport requests have arrived.</td></tr><?php else:foreach($recent as $request):?><tr><td><?= e($request['reference_code']) ?></td><td><?= e($request['full_name']) ?></td><td><?= e($request['produce_description']) ?> · <?= number_format((float)$request['quantity_kg'],0) ?> kg</td><td><?= e(date('j M Y',strtotime($request['pickup_date']))) ?></td><td><span class="status-pill <?= e($request['status']) ?>"><?= e(ucwords(str_replace('_',' ',$request['status']))) ?></span></td></tr><?php endforeach;endif;?></tbody></table></div></section>
<?php workspace_close(); ?>

