<?php
/** Orchard Ledger storage exchange: capacity, compatibility, and price are displayed before the request form. */
declare(strict_types=1);
require_once __DIR__ . '/../includes/bootstrap.php';

$facilities = fetch_all('SELECT sf.*, sp.id AS provider_id, sp.business_name, u.full_name AS contact_name, l.district, GROUP_CONCAT(DISTINCT pc.name ORDER BY pc.name SEPARATOR ", ") AS supported_products FROM storage_facilities sf JOIN storage_providers sp ON sp.id = sf.provider_id JOIN users u ON u.id = sp.user_id JOIN locations l ON l.id = sf.location_id LEFT JOIN facility_supported_products fsp ON fsp.facility_id = sf.id LEFT JOIN produce_categories pc ON pc.id = fsp.category_id WHERE sf.status = "active" GROUP BY sf.id ORDER BY sf.available_capacity_kg DESC');
$categories = fetch_all('SELECT id, name FROM produce_categories WHERE is_active = 1 ORDER BY name');
$farmer = current_user();
$farmerListings = $farmer !== null && $farmer['role_slug'] === 'farmer' ? fetch_all('SELECT id, title, category_id FROM produce_listings WHERE farmer_id = :farmer AND status = "active" ORDER BY title', ['farmer'=>$farmer['id']]) : [];
$pageTitle = 'Cold Storage';
require __DIR__ . '/../includes/header.php';
?>
<section class="service-hero"><div class="service-hero-copy"><span class="eyebrow">Cold-storage exchange</span><h1>Reserve the capacity that keeps a harvest market-ready.</h1><p>Review compatible produce, available capacity, storage type, and daily pricing before submitting a specific booking request.</p></div><div class="service-hero-image" style="background-image:url('/manus-storage/quetta-agrilink-storage_a1b611b7.jpg')"></div></section>
<section class="section"><div class="site-container"><div class="section-heading"><div><span class="eyebrow" style="color:var(--clay)">Available facilities</span><h2>Cold storage with terms you can inspect.</h2></div><p>Bookings remain requested until the facility provider reviews compatibility, dates, and capacity.</p></div><div class="service-grid"><?php if ($facilities === []): ?><div class="listing-empty"><h2>No active storage facilities yet.</h2><p>Facility providers can activate listed capacity from their workspace.</p></div><?php else: foreach ($facilities as $facility): ?><article class="service-card"><span class="badge"><?= e(ucwords(str_replace('_',' ',$facility['storage_type']))) ?></span><h2><?= e($facility['name']) ?></h2><p><?= e($facility['district']) ?>, Balochistan · <?= e($facility['business_name'] ?: $facility['contact_name']) ?></p><ul class="service-specs"><li><span>Available capacity</span><strong><?= number_format((float)$facility['available_capacity_kg'],0) ?> kg</strong></li><li><span>Total capacity</span><strong><?= number_format((float)$facility['total_capacity_kg'],0) ?> kg</strong></li><li><span>Daily price</span><strong>Rs. <?= number_format((float)$facility['price_per_kg_day'],2) ?>/kg</strong></li><li><span>Supported produce</span><strong><?= e($facility['supported_products'] ?: 'Provider to confirm') ?></strong></li></ul><?php if ($farmer !== null && $farmer['role_slug']==='farmer'): ?><a class="button button-primary" href="#book-storage" data-facility-id="<?= (int)$facility['id'] ?>">Request this capacity</a><?php else: ?><a class="button button-outline" href="<?= e(app_url('auth/login.php')) ?>">Sign in as farmer to request</a><?php endif; ?></article><?php endforeach; endif; ?></div></div></section>
<?php if ($farmer !== null && $farmer['role_slug'] === 'farmer'): ?><section class="section section-paper" id="book-storage"><div class="site-container booking-layout"><form action="<?= e(app_url('ajax/storage/book.php')) ?>" method="post" class="booking-form" data-ajax-form><span class="eyebrow" style="color:var(--clay)">Booking request</span><h2>Reserve cold storage</h2><p>The facility provider will review the request before capacity is committed. The estimate uses its current daily price and your requested dates.</p><input type="hidden" name="_csrf" value="<?= e(csrf_token()) ?>"><div class="booking-form-grid"><div class="form-field full"><label for="facility_id">Facility</label><select id="facility_id" name="facility_id" required><option value="">Choose a facility</option><?php foreach($facilities as $facility): ?><option value="<?= (int)$facility['id'] ?>"><?= e($facility['name']) ?> · <?= number_format((float)$facility['available_capacity_kg'],0) ?> kg available</option><?php endforeach;?></select></div><div class="form-field"><label for="listing_id">Your listed produce (optional)</label><select id="listing_id" name="listing_id"><option value="">Select later</option><?php foreach($farmerListings as $listing): ?><option value="<?= (int)$listing['id'] ?>"><?= e($listing['title']) ?></option><?php endforeach;?></select></div><div class="form-field"><label for="category_id">Produce type</label><select id="category_id" name="category_id" required><option value="">Choose produce</option><?php foreach($categories as $category): ?><option value="<?= (int)$category['id'] ?>"><?= e($category['name']) ?></option><?php endforeach;?></select></div><div class="form-field"><label for="quantity_kg">Quantity (kg)</label><input id="quantity_kg" name="quantity_kg" type="number" min="1" step="0.01" required></div><div class="form-field"><label for="start_date">Start date</label><input id="start_date" name="start_date" type="date" min="<?= date('Y-m-d') ?>" required></div><div class="form-field"><label for="end_date">End date</label><input id="end_date" name="end_date" type="date" min="<?= date('Y-m-d') ?>" required></div><div class="full" data-form-feedback></div><button class="button button-primary full" type="submit">Send booking request</button></div></form><aside class="booking-note"><span class="eyebrow">What happens next</span><h2>Terms are verified before storage begins.</h2><p>The provider sees requested produce, quantity, dates, and a calculated estimate. You receive an in-app notification when the request is approved, rejected, or activated.</p><ul><li>Capacity is checked against the facility’s available space.</li><li>Compatible produce is verified server-side.</li><li>Every booking status is recorded in its history.</li></ul></aside></div></section><?php endif; ?>
<?php require __DIR__ . '/../includes/footer.php'; ?>

