<?php
/** Orchard Ledger buyer dashboard: purchase commitments, offers, and saved discovery in one concise workspace. */
declare(strict_types=1);
require_once __DIR__ . '/../includes/bootstrap.php';
require_once __DIR__ . '/../includes/support-desk.php';
require_once __DIR__ . '/../includes/workspace.php';
$user=require_role(['buyer']);
$offers=fetch_one('SELECT COUNT(*) AS count FROM offers WHERE buyer_id=:user AND status IN("pending","countered")',['user'=>$user['id']]);$orders=fetch_one('SELECT COUNT(*) AS count FROM orders WHERE buyer_id=:user AND status NOT IN("completed","cancelled")',['user'=>$user['id']]);$completed=fetch_one('SELECT COUNT(*) AS count FROM orders WHERE buyer_id=:user AND status="completed"',['user'=>$user['id']]);$favorites=fetch_one('SELECT COUNT(*) AS count FROM favorites WHERE buyer_id=:user',['user'=>$user['id']]);
$supportAttention=support_desk_dashboard_attention($user);
workspace_open('Buyer dashboard','dashboard');render_status_cards([['label'=>'Active orders','value'=>(int)$orders['count'],'detail'=>'requiring follow-up'],['label'=>'Pending offers','value'=>(int)$offers['count'],'detail'=>'awaiting a response'],['label'=>'Support requests','value'=>$supportAttention['requester_open'],'detail'=>$supportAttention['available']?'open local records':'migration needed'],['label'=>'Completed purchases','value'=>(int)$completed['count'],'detail'=>'recorded in history'],['label'=>'Saved listings','value'=>(int)$favorites['count'],'detail'=>'shortlisted supply']]);
$recent=fetch_all('SELECT o.quantity,o.offered_price,o.status,o.created_at,pl.title,u.full_name AS farmer_name FROM offers o JOIN produce_listings pl ON pl.id=o.listing_id JOIN users u ON u.id=o.farmer_id WHERE o.buyer_id=:user ORDER BY o.created_at DESC LIMIT 6',['user'=>$user['id']]);
?>
<section class="workspace-section"><div class="workspace-section-header"><div><h2>Recent purchase offers</h2><p>Offers are recorded alongside their listing and supplier context.</p></div><a class="button button-outline" href="<?= e(app_url('marketplace/index.php')) ?>">Find produce</a></div><div class="data-table-wrap"><table class="data-table"><thead><tr><th>Produce</th><th>Farmer</th><th>Quantity</th><th>Your offer</th><th>Status</th></tr></thead><tbody><?php if($recent===[]):?><tr><td colspan="5">No purchase offers yet. Browse the marketplace to compare current supply.</td></tr><?php else:foreach($recent as $offer):?><tr><td><?= e($offer['title']) ?></td><td><?= e($offer['farmer_name']) ?></td><td><?= e((string)$offer['quantity']) ?> kg</td><td>Rs. <?= number_format((float)$offer['offered_price'],0) ?>/kg</td><td><span class="status-pill <?= e($offer['status']) ?>"><?= e(ucfirst($offer['status'])) ?></span></td></tr><?php endforeach;endif;?></tbody></table></div></section>
<section class="workspace-section"><div class="quick-links"><a class="quick-link" href="<?= e(app_url('marketplace/index.php')) ?>"><strong>Browse supply</strong><span>Filter current produce by origin, grade, price, and quantity.</span></a><a class="quick-link" href="<?= e(app_url('market-prices.php')) ?>"><strong>Review price records</strong><span>Use recorded local ranges as trade context.</span></a><a class="quick-link" href="<?= e(app_url('notifications.php')) ?>"><strong>Check alerts</strong><span>Track offer and order updates from the platform.</span></a></div></section>
<?php workspace_close(); ?>
