<?php
/** Orchard Ledger buyer offer desk: a farmer’s counterproposal remains a documented choice, not an informal message. */
declare(strict_types=1);
require_once __DIR__ . '/../includes/bootstrap.php';
require_once __DIR__ . '/../includes/workspace.php';
$user=require_role(['buyer']);$offers=fetch_all('SELECT o.*,pl.title,pl.unit,u.full_name AS farmer_name FROM offers o JOIN produce_listings pl ON pl.id=o.listing_id JOIN users u ON u.id=o.farmer_id WHERE o.buyer_id=:user ORDER BY FIELD(o.status,"countered","pending","accepted","rejected","withdrawn","expired"),o.created_at DESC',['user'=>$user['id']]);workspace_open('Purchase offers','offers');
?>
<section class="workspace-section"><div class="workspace-section-header"><div><h2>Offer status and counter terms</h2><p>A countered offer shows the most recent farmer terms. Accepting it creates an order with those terms.</p></div><a class="button button-outline" href="<?= e(app_url('marketplace/index.php')) ?>">Find produce</a></div><div class="data-table-wrap"><table class="data-table"><thead><tr><th>Listing</th><th>Farmer</th><th>Current terms</th><th>Status</th><th>Action</th></tr></thead><tbody><?php if($offers===[]):?><tr><td colspan="5">No offers have been sent yet.</td></tr><?php else:foreach($offers as $offer):?><tr><td><?= e($offer['title']) ?></td><td><?= e($offer['farmer_name']) ?></td><td><?= e((string)$offer['quantity']) ?> <?= e($offer['unit']) ?> · Rs. <?= number_format((float)$offer['offered_price'],2) ?>/<?= e($offer['unit']) ?></td><td><span class="status-pill <?= e($offer['status']) ?>"><?= e(ucfirst($offer['status'])) ?></span></td><td><?php if($offer['status']==='countered'):?><form action="<?= e(app_url('ajax/offers/respond.php')) ?>" method="post" data-ajax-form><input type="hidden" name="_csrf" value="<?= e(csrf_token()) ?>"><input type="hidden" name="offer_id" value="<?= (int)$offer['id'] ?>"><input type="hidden" name="action" value="accept"><button class="button button-primary" type="submit">Accept counter</button></form><form action="<?= e(app_url('ajax/offers/respond.php')) ?>" method="post" style="margin-top:6px" data-ajax-form><input type="hidden" name="_csrf" value="<?= e(csrf_token()) ?>"><input type="hidden" name="offer_id" value="<?= (int)$offer['id'] ?>"><input type="hidden" name="action" value="reject"><button class="button button-outline" type="submit">Decline</button></form><?php else:?><span class="muted">No action required</span><?php endif;?></td></tr><?php endforeach;endif;?></tbody></table></div></section>
<?php workspace_close(); ?>

