<?php
/** Orchard Ledger administrator dashboard: market health is summarized from authoritative operational records. */
declare(strict_types=1);
require_once __DIR__ . '/../includes/bootstrap.php';
require_once __DIR__ . '/../includes/support-desk.php';
require_once __DIR__ . '/../includes/workspace.php';
$user=require_role(['admin']);$summaryWindow=workspace_summary_window();$range=['from'=>$summaryWindow['from'],'to'=>$summaryWindow['to']];$users=fetch_one('SELECT COUNT(*) AS count FROM users WHERE status="active" AND created_at >= :from AND created_at < :to',$range);$listings=fetch_one('SELECT COUNT(*) AS count FROM produce_listings WHERE status="active" AND created_at >= :from AND created_at < :to',$range);$orders=fetch_one('SELECT COUNT(*) AS count FROM orders WHERE created_at >= :from AND created_at < :to',$range);$capacity=fetch_one('SELECT COALESCE(SUM(total_capacity_kg),0) AS total,COALESCE(SUM(available_capacity_kg),0) AS available FROM storage_facilities WHERE status="active"');$supportAttention=support_desk_dashboard_attention($user);$totalCapacity=(float)$capacity['total'];
workspace_open('Administrator dashboard','dashboard');render_status_cards([['label'=>'Active users','value'=>(int)$users['count'],'detail'=>'created in selected period'],['label'=>'Active listings','value'=>(int)$listings['count'],'detail'=>'created in selected period'],['label'=>'Total orders','value'=>(int)$orders['count'],'detail'=>'created in selected period'],['label'=>'Support attention','value'=>$supportAttention['queue_open'],'detail'=>$supportAttention['available']?'open local requests':'migration needed'],['label'=>'Storage utilization','value'=>$totalCapacity>0?(int)round((1-((float)$capacity['available']/$totalCapacity))*100).'%':'0%','detail'=>'current listed capacity in use']],$summaryWindow);$recent=fetch_all('SELECT u.full_name,u.email,u.status,r.name AS role_name,u.created_at FROM users u JOIN roles r ON r.id=u.role_id ORDER BY u.created_at DESC LIMIT 8');
?>
<section class="workspace-section"><div class="workspace-section-header"><div><h2>Recent accounts</h2><p>Review role and account status.</p></div></div><div class="data-table-wrap"><table class="data-table"><thead><tr><th>Account</th><th>Role</th><th>Email</th><th>Status</th><th>Created</th></tr></thead><tbody><?php foreach($recent as $account):?><tr><td><?= e($account['full_name']) ?></td><td><?= e($account['role_name']) ?></td><td><?= e($account['email']) ?></td><td><span class="status-pill"><?= e(ucfirst($account['status'])) ?></span></td><td><?= e(date('j M Y',strtotime($account['created_at']))) ?></td></tr><?php endforeach;?></tbody></table></div></section>
<?php workspace_close(); ?>
