<?php
/** Orchard Ledger administrator dashboard: market health is summarized from authoritative operational records. */
declare(strict_types=1);
require_once __DIR__ . '/../includes/bootstrap.php';
require_once __DIR__ . '/../includes/support-desk.php';
require_once __DIR__ . '/../includes/workspace.php';
$user=require_role(['admin']);$summaryWindow=workspace_summary_window();$range=['from'=>$summaryWindow['from'],'to'=>$summaryWindow['to']];$users=fetch_one('SELECT COUNT(*) AS count FROM users WHERE status="active" AND created_at >= :from AND created_at < :to',$range);$listings=fetch_one('SELECT COUNT(*) AS count FROM produce_listings WHERE status="active" AND created_at >= :from AND created_at < :to',$range);$orders=fetch_one('SELECT COUNT(*) AS count,COALESCE(SUM(total_amount),0) AS value,SUM(status="completed") AS completed FROM orders WHERE created_at >= :from AND created_at < :to',$range);$capacity=fetch_one('SELECT COALESCE(SUM(total_capacity_kg),0) AS total,COALESCE(SUM(available_capacity_kg),0) AS available FROM storage_facilities WHERE status="active"');$supportAttention=support_desk_dashboard_attention($user);$totalCapacity=(float)$capacity['total'];$roleCounts=fetch_all('SELECT r.name,COUNT(u.id) AS count FROM roles r LEFT JOIN users u ON u.role_id=r.id AND u.status="active" GROUP BY r.id ORDER BY r.id');$topProducts=fetch_all('SELECT pc.name,COUNT(DISTINCT pl.id) AS listings,COALESCE(SUM(oi.line_total),0) AS sales FROM produce_categories pc LEFT JOIN produce_listings pl ON pl.category_id=pc.id LEFT JOIN order_items oi ON oi.category_id=pc.id GROUP BY pc.id ORDER BY sales DESC,listings DESC LIMIT 6');$monthly=fetch_all('SELECT DATE_FORMAT(created_at,"%Y-%m") AS month,COUNT(*) AS orders,COALESCE(SUM(total_amount),0) AS value FROM orders WHERE created_at>=DATE_SUB(CURDATE(),INTERVAL 5 MONTH) GROUP BY DATE_FORMAT(created_at,"%Y-%m") ORDER BY month');
workspace_open('Administrator dashboard','dashboard');render_status_cards([['label'=>'Active users','value'=>(int)$users['count'],'detail'=>'created in selected period'],['label'=>'Active listings','value'=>(int)$listings['count'],'detail'=>'created in selected period'],['label'=>'Orders / completed','value'=>(int)$orders['count'].' / '.(int)$orders['completed'],'detail'=>'created in selected period'],['label'=>'Marketplace value','value'=>'Rs. '.number_format((float)$orders['value'],0),'detail'=>'selected-period order value'],['label'=>'Storage utilization','value'=>$totalCapacity>0?(int)round((1-((float)$capacity['available']/$totalCapacity))*100).'%':'0%','detail'=>'current listed capacity in use']],$summaryWindow);$recent=fetch_all('SELECT u.full_name,u.email,u.status,r.name AS role_name,u.created_at FROM users u JOIN roles r ON r.id=u.role_id ORDER BY u.created_at DESC LIMIT 8');
$transportActivity=fetch_all('SELECT status,COUNT(*) AS count,COALESCE(SUM(COALESCE(final_price,estimated_price)),0) AS value FROM transport_requests GROUP BY status ORDER BY count DESC'); ?>
<section class="workspace-section"><div class="workspace-section-header"><div><h2>Recent accounts</h2><p>Review role and account status.</p></div></div><div class="data-table-wrap"><table class="data-table"><thead><tr><th>Account</th><th>Role</th><th>Email</th><th>Status</th><th>Created</th></tr></thead><tbody><?php foreach($recent as $account):?><tr><td><?= e($account['full_name']) ?></td><td><?= e($account['role_name']) ?></td><td><?= e($account['email']) ?></td><td><span class="status-pill"><?= e(ucfirst($account['status'])) ?></span></td><td><?= e(date('j M Y',strtotime($account['created_at']))) ?></td></tr><?php endforeach;?></tbody></table></div></section>
<section class="workspace-section analytics-grid"><div><h2>Active accounts by role</h2><?php foreach($roleCounts as $role):?><div class="analytics-row"><span><?= e($role['name']) ?></span><strong><?= (int)$role['count'] ?></strong></div><?php endforeach;?></div><div><h2>Top produce activity</h2><?php if($topProducts===[]):?><p class="muted">No produce activity yet.</p><?php else:foreach($topProducts as $product):?><div class="analytics-row"><span><?= e($product['name']) ?> · <?= (int)$product['listings'] ?> listings</span><strong>Rs. <?= number_format((float)$product['sales'],0) ?></strong></div><?php endforeach;endif;?></div><div><h2>Orders over six months</h2><?php if($monthly===[]):?><p class="muted">No order time series yet.</p><?php else:foreach($monthly as $point):?><div class="analytics-row"><span><?= e(date('M Y',strtotime($point['month'].'-01'))) ?></span><strong><?= (int)$point['orders'] ?> · Rs. <?= number_format((float)$point['value'],0) ?></strong></div><?php endforeach;endif;?></div></section>
<section class="workspace-section"><div class="workspace-section-header"><div><h2>Transport activity</h2><p>Current request volume and recorded value by dispatch milestone.</p></div></div><div class="analytics-grid"><?php if($transportActivity===[]):?><p class="muted">No transport activity yet.</p><?php else:foreach($transportActivity as $activity):?><div class="analytics-row"><span><?= e(order_status_label($activity['status'])) ?></span><strong><?= (int)$activity['count'] ?> · Rs. <?= number_format((float)$activity['value'],0) ?></strong></div><?php endforeach;endif;?></div></section>
<?php workspace_close(); ?>
