<?php
declare(strict_types=1);
require_once __DIR__ . '/../../includes/bootstrap.php';
require_method('POST'); verify_csrf(); $farmer = require_role(['farmer']);
$facilityId=filter_input(INPUT_POST,'facility_id',FILTER_VALIDATE_INT,['options'=>['min_range'=>1]]); $listingId=filter_input(INPUT_POST,'listing_id',FILTER_VALIDATE_INT,['options'=>['min_range'=>1]]) ?: null; $categoryId=filter_input(INPUT_POST,'category_id',FILTER_VALIDATE_INT,['options'=>['min_range'=>1]]); $quantity=positive_decimal($_POST['quantity_kg']??null); $start=$_POST['start_date']??''; $end=$_POST['end_date']??'';
$startDate=DateTimeImmutable::createFromFormat('!Y-m-d',$start); $endDate=DateTimeImmutable::createFromFormat('!Y-m-d',$end);
if(!$facilityId || !$categoryId || $quantity===null || !$startDate || !$endDate || $endDate < $startDate) json_response(false,'Enter a valid facility, produce, positive quantity, and date range.',[],422);
$pdo=db();$pdo->beginTransaction();
try{$facility=fetch_one('SELECT sf.*,sp.user_id AS provider_user_id FROM storage_facilities sf JOIN storage_providers sp ON sp.id=sf.provider_id WHERE sf.id=:id AND sf.status="active" FOR UPDATE',['id'=>$facilityId]);if($facility===null)throw new RuntimeException('This storage facility is not currently available.');$supports=fetch_one('SELECT facility_id FROM facility_supported_products WHERE facility_id=:facility AND category_id=:category LIMIT 1',['facility'=>$facilityId,'category'=>$categoryId]);if($supports===null)throw new RuntimeException('This facility has not listed support for the selected produce.');if($quantity>(float)$facility['available_capacity_kg'])throw new RuntimeException('The requested quantity exceeds the facility’s available capacity.');if($listingId!==null && fetch_one('SELECT id FROM produce_listings WHERE id=:listing AND farmer_id=:farmer LIMIT 1',['listing'=>$listingId,'farmer'=>$farmer['id']])===null)throw new RuntimeException('The selected listing is not owned by your account.');$days=max(1,(int)$startDate->diff($endDate)->days);$estimate=round($quantity*(float)$facility['price_per_kg_day']*$days,2);$reference=generate_reference('QAS');$pdo->prepare('INSERT INTO storage_bookings (reference_code,farmer_id,facility_id,listing_id,category_id,quantity_kg,start_date,end_date,price_per_kg_day,estimated_cost) VALUES (:reference,:farmer,:facility,:listing,:category,:quantity,:start,:end,:price,:estimate)')->execute(['reference'=>$reference,'farmer'=>$farmer['id'],'facility'=>$facilityId,'listing'=>$listingId,'category'=>$categoryId,'quantity'=>$quantity,'start'=>$startDate->format('Y-m-d'),'end'=>$endDate->format('Y-m-d'),'price'=>$facility['price_per_kg_day'],'estimate'=>$estimate]);$bookingId=(int)$pdo->lastInsertId();$pdo->prepare('INSERT INTO storage_booking_status_history (booking_id,status,changed_by_user_id,note) VALUES (:booking,"requested",:actor,:note)')->execute(['booking'=>$bookingId,'actor'=>$farmer['id'],'note'=>'Farmer booking request submitted.']);create_notification((int)$facility['provider_user_id'],'storage_booking_requested','New storage booking request',$farmer['full_name'].' requested '.number_format($quantity,0).' kg from '.$startDate->format('j M').' to '.$endDate->format('j M Y').'.','storage/bookings.php','storage_booking',$bookingId);$pdo->commit();audit_log((int)$farmer['id'],'storage_booking_requested','storage_bookings',$bookingId,['reference'=>$reference]);json_response(true,'Storage booking request sent. Estimated cost: Rs. '.number_format($estimate,2).'.',['booking_id'=>$bookingId,'reference'=>$reference]);}catch(Throwable $e){if($pdo->inTransaction())$pdo->rollBack();json_response(false,$e instanceof RuntimeException?$e->getMessage():'The booking request could not be saved.',[],422);}

