<?php
/** Orchard Ledger farmer offer desk: negotiation is explicit and every accepted term becomes an order record. */
declare(strict_types=1);
require_once __DIR__ . '/../includes/bootstrap.php';
require_once __DIR__ . '/../includes/workspace.php';
$user=require_role(['farmer']);$offers=fetch_all('SELECT o.*,pl.title,pl.unit,u.full_name AS buyer_name FROM offers o JOIN produce_listings pl ON pl.id=o.listing_id JOIN users u ON u.id=o.buyer_id WHERE o.farmer_id=:user ORDER BY FIELD(o.status,"pending","countered","accepted","rejected","withdrawn","expired"),o.created_at DESC',['user'=>$user['id']]);workspace_open('Offer desk','offers');
?>
<section class="workspace-section"><div class="workspace-section-header"><div><h2>Buyer proposals</h2><p>Accept a viable offer, reject it with a recorded outcome, or return specific counter terms.</p></div><span class="status-pill"><?= count($offers) ?> total</span></div><div class="data-table-wrap"><table class="data-table"><thead><tr><th>Listing</th><th>Buyer</th><th>Proposed terms</th><th>Status</th><th>Action</th></tr></thead><tbody><?php if($offers===[]):?><tr><td colspan="5">No buyer offers have been received.</td></tr><?php else:foreach($offers as $offer):?><tr><td><strong><?= e($offer['title']) ?></strong><br><span class="muted"><?= e(date('j M Y',strtotime($offer['created_at']))) ?></span></td><td><?= e($offer['buyer_name']) ?></td><td><?= e((string)$offer['quantity']) ?> <?= e($offer['unit']) ?> · Rs. <?= number_format((float)$offer['offered_price'],2) ?>/<?= e($offer['unit']) ?><br><strong>Rs. <?= number_format((float)$offer['total_amount'],2) ?></strong></td><td><span class="status-pill <?= e($offer['status']) ?>"><?= e(ucfirst($offer['status'])) ?></span></td><td><?php if(in_array($offer['status'],['pending','countered'],true)):?><form class="inline-form" action="<?= e(app_url('ajax/offers/respond.php')) ?>" method="post" data-ajax-form><input type="hidden" name="_csrf" value="<?= e(csrf_token()) ?>"><input type="hidden" name="offer_id" value="<?= (int)$offer['id'] ?>"><input type="hidden" name="action" value="accept"><button class="button button-primary" type="submit">Accept</button></form><form class="inline-form" style="margin-top:6px" action="<?= e(app_url('ajax/offers/respond.php')) ?>" method="post" data-ajax-form><input type="hidden" name="_csrf" value="<?= e(csrf_token()) ?>"><input type="hidden" name="offer_id" value="<?= (int)$offer['id'] ?>"><input type="hidden" name="action" value="reject"><button class="button button-outline" type="submit">Reject</button></form><details style="margin-top:8px"><summary class="muted" style="font-size:12px;cursor:pointer">Counter terms</summary><form action="<?= e(app_url('ajax/offers/respond.php')) ?>" method="post" class="form-grid" style="margin-top:8px" data-ajax-form><input type="hidden" name="_csrf" value="<?= e(csrf_token()) ?>"><input type="hidden" name="offer_id" value="<?= (int)$offer['id'] ?>"><input type="hidden" name="action" value="counter"><div class="form-field"><label>Quantity</label><input name="quantity" type="number" min="1" step=".01" value="<?= e((string)$offer['quantity']) ?>"></div><div class="form-field"><label>Price / <?= e($offer['unit']) ?></label><input name="offered_price" type="number" min="1" step=".01" value="<?= e((string)$offer['offered_price']) ?>"></div><button class="button button-quiet" type="submit">Send counter</button></form></details><?php else:?><span class="muted">No action required</span><?php endif;?></td></tr><?php endforeach;endif;?></tbody></table></div></section>
<?php workspace_close(); ?>

